-- Registre prive des abonnements Stripe.
-- A appliquer apres supabase_profile_usernames.sql.
-- Cette migration ne modifie ni le tableur, ni les objectifs, ni les partages.

create table if not exists public.billing_customers (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text not null unique check (stripe_customer_id ~ '^cus_[A-Za-z0-9]+$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.billing_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text not null check (stripe_customer_id ~ '^cus_[A-Za-z0-9]+$'),
  stripe_subscription_id text unique check (stripe_subscription_id is null or stripe_subscription_id ~ '^sub_[A-Za-z0-9]+$'),
  stripe_price_id text check (stripe_price_id is null or stripe_price_id ~ '^price_[A-Za-z0-9]+$'),
  plan text not null default 'free' check (plan in ('free','plus','pro')),
  status text not null default 'none' check (status in ('none','incomplete','incomplete_expired','trialing','active','past_due','canceled','unpaid','paused')),
  access_granted boolean not null default false,
  cancel_at_period_end boolean not null default false,
  current_period_end timestamptz,
  subscription_started_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.billing_checkout_limits (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null check (plan in ('plus','pro')),
  last_attempt_at timestamptz not null default now()
);

create table if not exists public.billing_webhook_events (
  stripe_event_id text primary key check (stripe_event_id ~ '^evt_[A-Za-z0-9]+$'),
  event_type text not null,
  event_created_at timestamptz not null,
  livemode boolean not null,
  state text not null default 'processing' check (state in ('processing','processed','failed')),
  error_code text,
  updated_at timestamptz not null default now()
);

create table if not exists public.billing_grants (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan text not null check (plan in ('plus','pro')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  revoked_at timestamptz,
  reason text not null check (char_length(reason) between 3 and 240),
  created_by text not null check (char_length(created_by) between 3 and 320),
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create index if not exists billing_grants_user_active_idx
  on public.billing_grants(user_id, ends_at desc) where revoked_at is null;

alter table public.billing_customers enable row level security;
alter table public.billing_subscriptions enable row level security;
alter table public.billing_checkout_limits enable row level security;
alter table public.billing_webhook_events enable row level security;
alter table public.billing_grants enable row level security;

revoke all on public.billing_customers, public.billing_subscriptions,
  public.billing_checkout_limits, public.billing_webhook_events
  , public.billing_grants
  from public, anon, authenticated;
grant select, insert, update, delete on public.billing_customers,
  public.billing_subscriptions, public.billing_checkout_limits,
  public.billing_webhook_events, public.billing_grants to service_role;
grant usage, select on sequence public.billing_grants_id_seq to service_role;

create or replace function public.begin_billing_checkout(p_user_id uuid, p_plan text)
returns timestamptz
language plpgsql
security definer
set search_path = ''
as $$
declare last_attempt timestamptz;
begin
  if p_plan not in ('plus','pro') then raise exception 'invalid_plan'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_user_id::text, 0));
  select b.last_attempt_at into last_attempt from public.billing_checkout_limits b where b.user_id=p_user_id for update;
  if last_attempt is not null and last_attempt > now()-interval '30 seconds' then
    raise exception 'checkout_rate_limited';
  end if;
  insert into public.billing_checkout_limits(user_id,plan,last_attempt_at)
    values(p_user_id,p_plan,now())
    on conflict(user_id) do update set plan=excluded.plan,last_attempt_at=excluded.last_attempt_at;
  return now();
end;
$$;
revoke all on function public.begin_billing_checkout(uuid,text) from public, anon, authenticated;
grant execute on function public.begin_billing_checkout(uuid,text) to service_role;

create or replace function public.claim_stripe_webhook_event(
  p_event_id text, p_event_type text, p_event_created bigint, p_livemode boolean
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare current_record public.billing_webhook_events%rowtype;
begin
  if p_event_id !~ '^evt_[A-Za-z0-9]+$' or length(p_event_type)>160 then raise exception 'invalid_event'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_event_id,0));
  select * into current_record from public.billing_webhook_events where stripe_event_id=p_event_id for update;
  if found and current_record.state='processed' then return false; end if;
  if found and current_record.state='processing' and current_record.updated_at>now()-interval '5 minutes' then return false; end if;
  insert into public.billing_webhook_events(stripe_event_id,event_type,event_created_at,livemode,state,error_code,updated_at)
    values(p_event_id,p_event_type,to_timestamp(p_event_created),p_livemode,'processing',null,now())
    on conflict(stripe_event_id) do update set state='processing',error_code=null,updated_at=now();
  return true;
end;
$$;
revoke all on function public.claim_stripe_webhook_event(text,text,bigint,boolean) from public, anon, authenticated;
grant execute on function public.claim_stripe_webhook_event(text,text,bigint,boolean) to service_role;

create or replace function public.complete_stripe_webhook_event(p_event_id text, p_error text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.billing_webhook_events
    set state=case when p_error is null then 'processed' else 'failed' end,
        error_code=left(p_error,80),updated_at=now()
    where stripe_event_id=p_event_id;
end;
$$;
revoke all on function public.complete_stripe_webhook_event(text,text) from public, anon, authenticated;
grant execute on function public.complete_stripe_webhook_event(text,text) to service_role;

-- Le navigateur peut lire son plan par la fonction existante, sans recevoir
-- les identifiants Stripe ni les donnees de facturation internes.
create or replace function public.get_my_profile()
returns table(username text, username_changed_at timestamptz, created_at timestamptz, plan text, subscription_started_at timestamptz)
language plpgsql security definer set search_path = '' as $$
declare current_user_record auth.users%rowtype;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  select * into current_user_record from auth.users where id=auth.uid();
  if not found then raise exception 'not_authenticated'; end if;
  insert into public.profiles(id,email,display_name,created_at)
    values(current_user_record.id,current_user_record.email,
      split_part(coalesce(current_user_record.email,''),'@',1),current_user_record.created_at)
    on conflict (id) do nothing;
  return query
    select p.username,p.username_changed_at,current_user_record.created_at,
      case
        when g.plan='pro' then 'pro'
        when b.access_granted and b.status in ('active','trialing') and b.plan='pro' then 'pro'
        when g.plan='plus' then 'plus'
        when b.access_granted and b.status in ('active','trialing') and b.plan='plus' then 'plus'
        else 'free'
      end,
      case
        when g.plan='pro' or (g.plan='plus' and not (b.access_granted and b.status in ('active','trialing') and b.plan='pro')) then g.starts_at
        when b.access_granted then b.subscription_started_at
        else null
      end
    from public.profiles p
    left join public.billing_subscriptions b on b.user_id=p.id
    left join lateral (
      select bg.plan,bg.starts_at,bg.ends_at
      from public.billing_grants bg
      where bg.user_id=p.id and bg.revoked_at is null and bg.starts_at<=now() and bg.ends_at>now()
      order by case bg.plan when 'pro' then 2 else 1 end desc,bg.ends_at desc
      limit 1
    ) g on true
    where p.id=auth.uid();
end;
$$;
revoke all on function public.get_my_profile() from public, anon;
grant execute on function public.get_my_profile() to authenticated;
